import Link from 'next/link'
import { notFound } from 'next/navigation'
import { prisma } from '@/lib/prisma'
import { formatPaymentMethodLabel } from '@/lib/payments/receipts'

export const dynamic = 'force-dynamic'

function money(v: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(v || 0))
}

export default async function PublicPaymentReceiptPage({
  params,
}: {
  params: { token: string }
}) {
  const token = String(params.token || '').trim()
  if (!token) notFound()

  const payment = await prisma.payment.findFirst({
    where: { receiptToken: token },
    include: {
      invoice: {
        include: {
          tenant: { select: { name: true } },
          client: { select: { name: true } },
        },
      },
    },
  })

  if (!payment?.invoice) notFound()
  if (payment.receiptTokenExpiresAt && payment.receiptTokenExpiresAt.getTime() <= Date.now()) notFound()

  const methodLabel = formatPaymentMethodLabel(payment)

  return (
    <div className="mx-auto max-w-2xl p-6">
      <div className="rounded-xl border bg-white p-6 shadow-sm">
        <h1 className="text-2xl font-bold text-gray-900">Payment Receipt</h1>
        <p className="mt-2 text-sm text-gray-600">This receipt was generated by TrimPro for your payment.</p>

        <div className="mt-5 space-y-2 text-sm">
          <div>
            <span className="text-gray-500">Company:</span> <span className="font-semibold">{payment.invoice.tenant?.name || 'TrimPro'}</span>
          </div>
          <div>
            <span className="text-gray-500">Customer:</span> <span className="font-semibold">{payment.invoice.client?.name || 'Customer'}</span>
          </div>
          <div>
            <span className="text-gray-500">Invoice:</span> <span className="font-semibold">{payment.invoice.invoiceNumber}</span>
          </div>
          <div>
            <span className="text-gray-500">Amount paid:</span> <span className="font-semibold">{money(Number(payment.amount || 0))}</span>
          </div>
          <div>
            <span className="text-gray-500">Method:</span> <span className="font-semibold">{methodLabel}</span>
          </div>
          <div>
            <span className="text-gray-500">Payment date:</span>{' '}
            <span className="font-semibold">{(payment.processedAt || payment.createdAt).toLocaleString()}</span>
          </div>
          {payment.providerPaymentId ? (
            <div>
              <span className="text-gray-500">QuickBooks payment ID:</span>{' '}
              <span className="font-semibold">{payment.providerPaymentId}</span>
            </div>
          ) : null}
          {payment.providerInvoiceId ? (
            <div>
              <span className="text-gray-500">QuickBooks invoice ID:</span>{' '}
              <span className="font-semibold">{payment.providerInvoiceId}</span>
            </div>
          ) : null}
        </div>

        <div className="mt-6">
          <Link
            href={`/portal/pay/${payment.invoice.id}`}
            className="inline-flex items-center justify-center rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50"
          >
            View invoice
          </Link>
        </div>
      </div>
    </div>
  )
}
