// ─── Smart Steps ABA Tracker — Type System ───────────────────────────────────
// Clinically bulletproof, production-grade, built different 💜

export type ABARole = 'RBT' | 'BCBA' | 'ADMIN' | 'PARENT'

export type Domain =
  | 'Mand' | 'Tact' | 'Intraverbal' | 'Echoic' | 'Social'
  | 'ADL' | 'Academic' | 'Motor' | 'Play' | 'Behavior' | 'Custom'

export type TargetType =
  | 'discrete_trial'
  | 'task_analysis_forward'
  | 'task_analysis_backward'
  | 'task_analysis_total'
  | 'cold_probe'
  | 'generalization_probe'
  | 'duration'
  | 'latency'
  | 'frequency'
  | 'interval_partial'
  | 'interval_whole'
  | 'interval_momentary'

export type Phase = 'baseline' | 'acquisition' | 'maintenance' | 'generalization' | 'mastered' | 'on_hold'

export type TrialResult = 'correct' | 'incorrect' | 'prompted' | 'no_response' | 'skipped'

export type BehaviorIntensity = 'mild' | 'moderate' | 'severe'

export type SessionStatus = 'active' | 'paused' | 'completed' | 'cancelled'

export type SyncStatus = 'synced' | 'pending' | 'conflict' | 'error'

// ─── Core Models ──────────────────────────────────────────────────────────────

export interface ABAClient {
  id: string
  firstName: string
  lastName: string
  dob: string // ISO date
  age: number
  photoUrl?: string
  diagnosisTags: string[]
  assignedTherapists: string[] // user IDs
  insuranceId?: string
  guardianName?: string
  guardianPhone?: string
  guardianEmail?: string
  notes?: string
  createdAt: string
  updatedAt: string
  // computed
  lastSessionDate?: string
  overallProgress?: number // 0–100 %
  masteredTargets?: number
  totalTargets?: number
  sessionsThisWeek?: number
}

export interface PromptLevel {
  id: string
  level: number // 0 = independent
  label: string // 'Independent', 'Verbal', 'Gestural', ...
  abbreviation: string // 'I', 'V', 'G', 'PP', 'FP'
  color: string // hex
}

export interface MasteryRule {
  id: string
  targetId: string
  percentCorrect: number // e.g. 80
  consecutiveSessions: number // e.g. 3
  minTrialsPerSession: number // e.g. 10
  maxPromptLevel: number // 0 = independent only
  autoAdvance: boolean
}

export interface Program {
  id: string
  clientId: string
  name: string
  domain: Domain
  description?: string
  isActive: boolean
  createdByRole: ABARole
  createdAt: string
  updatedAt: string
  targets?: Target[]
}

export interface Target {
  id: string
  programId: string
  clientId: string
  name: string
  operationalDefinition: string
  type: TargetType
  phase: Phase
  masteryRule?: MasteryRule
  promptLevels?: PromptLevel[]
  stimuli?: string[] // for rotation
  isActive: boolean
  sortOrder: number
  createdAt: string
  updatedAt: string
  // computed
  recentAccuracy?: number // last session %
  trend?: 'up' | 'down' | 'flat' | 'plateau'
  trialCount?: number
  plateauDays?: number
}

export interface Session {
  id: string
  clientId: string
  therapistId: string
  therapistName: string
  startTime: string // ISO
  endTime?: string // ISO
  status: SessionStatus
  targetIds: string[]
  notes?: string
  location?: string
  createdAt: string
  updatedAt: string
  syncStatus: SyncStatus
  // computed
  trialCount?: number
  correctPercent?: number
  masteredToday?: string[] // target IDs
}

export interface Trial {
  id: string
  sessionId: string
  targetId: string
  clientId: string
  result: TrialResult
  promptLevel?: number // 0 = independent
  latencyMs?: number
  durationMs?: number
  timestamp: string // ISO
  therapistId: string
  notes?: string
  syncStatus: SyncStatus
}

export interface BehaviorEvent {
  id: string
  sessionId: string
  clientId: string
  behaviorName: string
  type: 'frequency' | 'duration' | 'abc'
  count?: number
  startTime?: string
  endTime?: string
  durationMs?: number
  antecedent?: string
  consequence?: string
  intensity?: BehaviorIntensity
  location?: string
  staffPresent?: string[]
  tags?: string[]
  notes?: string
  timestamp: string
  therapistId: string
  syncStatus: SyncStatus
}

export interface Note {
  id: string
  clientId: string
  sessionId?: string
  authorId: string
  authorName: string
  type: 'session' | 'progress' | 'soap' | 'general'
  content: string
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

// ─── Analytics ────────────────────────────────────────────────────────────────

export interface TargetDataPoint {
  date: string
  percent: number
  trials: number
  prompted: number
  correct: number
  incorrect: number
  sessionId: string
}

export interface BehaviorDataPoint {
  date: string
  count: number
  avgDuration?: number
  intensity?: Record<BehaviorIntensity, number>
}

export interface ClientStats {
  masteredTargets: number
  totalTargets: number
  activeTargets: number
  sessionsThisWeek: number
  totalTrialsThisMonth: number
  avgAccuracyThisWeek: number
  plateauAlerts: number
  masteryRate: number // % targets mastered of total
  topBehaviors: Array<{ name: string; count: number; trend: 'up' | 'down' | 'flat' }>
}

// ─── Session Entry State ──────────────────────────────────────────────────────

export interface ActiveSessionState {
  sessionId: string
  clientId: string
  startTime: number // epoch ms
  pausedMs: number // total paused ms
  isPaused: boolean
  selectedTargets: string[]
  currentTargetIndex: number
  pendingTrials: Trial[]
  pendingBehaviors: BehaviorEvent[]
  undoStack: Array<{ type: 'trial' | 'behavior'; id: string }>
  intervalConfig?: {
    type: 'partial' | 'whole' | 'momentary'
    intervalMs: number
    running: boolean
    nextAlertAt: number
  }
}

// ─── Sync Queue ───────────────────────────────────────────────────────────────

export interface SyncQueueItem {
  id: string
  type: 'trial' | 'behavior' | 'session' | 'note'
  operation: 'create' | 'update' | 'delete'
  payload: unknown
  timestamp: string
  retries: number
  error?: string
}

// ─── Gamification ─────────────────────────────────────────────────────────────

export interface Badge {
  id: string
  label: string
  description: string
  icon: string
  earnedAt?: string
  threshold: number
}

export const BADGES: Badge[] = [
  { id: 'first_session', label: 'First Session', description: 'Completed your first session', icon: '🎯', threshold: 1 },
  { id: 'trial_100', label: 'Century Club', description: '100 trials logged', icon: '💯', threshold: 100 },
  { id: 'trial_1000', label: 'Data Beast', description: '1,000 trials logged', icon: '🦁', threshold: 1000 },
  { id: 'trial_10000', label: 'ABA Legend', description: '10,000 trials logged', icon: '🏆', threshold: 10000 },
  { id: 'mastery_1', label: 'First Mastery', description: 'First target mastered', icon: '⭐', threshold: 1 },
  { id: 'mastery_10', label: 'Mastery Machine', description: '10 targets mastered', icon: '🌟', threshold: 10 },
  { id: 'streak_5', label: 'On Fire', description: '5-day session streak', icon: '🔥', threshold: 5 },
  { id: 'streak_30', label: 'Unstoppable', description: '30-day session streak', icon: '⚡', threshold: 30 },
]

export const DEFAULT_PROMPT_LEVELS: PromptLevel[] = [
  { id: 'p0', level: 0, label: 'Independent', abbreviation: 'I', color: '#10b981' },
  { id: 'p1', level: 1, label: 'Verbal', abbreviation: 'V', color: '#3b82f6' },
  { id: 'p2', level: 2, label: 'Gestural', abbreviation: 'G', color: '#8b5cf6' },
  { id: 'p3', level: 3, label: 'Partial Physical', abbreviation: 'PP', color: '#f59e0b' },
  { id: 'p4', level: 4, label: 'Full Physical', abbreviation: 'FP', color: '#ef4444' },
]
